### ISSUE TITLE
Video not showing up on awesome-manim page

### ISSUE THREAD

**Issue by negvoss** [ManimCommunity/awesome-manim#54]
Hi,

A couple days ago, my pull request for my Youtube channel PurpleMind (youtube.com/@PurpleMindCS) was merged into the main branch. Much thanks to the community for welcoming me in!

I'm wondering why my first video is still not showing up on the awesome-manim page. If anyone knows, please let me know what I can do.

Thanks

**Comment by lucasricci** [comment]
@negvoss The website can take some time to update the videos, since the webcrawler runs from time to time. Probably it will appear in the following days

**Comment by negvoss** [comment]
@lucasricci Okay, thanks!

**Comment by negvoss** [comment]
Hmm, still not showing up. Is it possible that posting the video as a premiere before my pull request was merged caused the video to not get noticed?

**Comment by lucasricci** [comment]
Hum, idk. @naveen521kk, was there any issue with the crawler recently?

**Comment by naveen521kk** [comment]
@negvoss the crawler expects "manim" mentioned in description or something similar. That's done so that we don't show all the videos the user creates and instead only show the ones they create using manim.

See https://github.com/ManimCommunity/manim-website-api/blob/690eaebed7848952d03f206aeaf7dcb9917cd922/updator/helper.py#L64 for the things we check.

**Comment by negvoss** [comment]
Aha! Thanks. I will update the description.

**Comment by naveen521kk** [comment]
I could see your video on the website. I assume this issue is fixed and I'm closing this issue.

**Comment by negvoss** [comment]
Thank you!!
